---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:r0t0/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: latest
    replicaCount: 1
    hpa:
      enabled: false
